### ISSUE TITLE
提几个建议 希望大佬能采纳

### ISSUE THREAD

**Issue by dahai0401** [tdp-resource/tdp-cloud#25]
1.能不能让多个账号的虚拟机列表全部显示，可以不需要一个一个账号切换
2.能不能增加重装系统，修改密码等基础功能
3.能不能隐藏一些不需要的功能，针对配置文件控制的，比如说我只需要个轻量云其他都不需要

**Comment by rehiy** [comment]
1、有考虑过，目前资源管理模式受限于腾讯云接口请求速率，无法实现太多资源的转态拉取。后续会改变一些核心代码去实施这个操作。
2、由于通过接口进行这些操作无需二次鉴权，所以暂未支持。在没有好的二次鉴权功能前不打算增加这个风险操作
3、这个的确是计划实施的一部分，后期会支持功能和页面的自定义

**Comment by rehiy** [comment]
1、已实现
