### ISSUE TITLE
解析记录添加失败后保存按钮会卡死，需要重新刷新网页才能恢复正常

### ISSUE THREAD

**Issue by hapke24** [tdp-resource/tdp-cloud#26]
### 复现方法

首先输入一个错误的记录值，例如：
![image](https://user-images.githubusercontent.com/49407099/188849366-feaf8431-49f6-41bc-8afe-ee928e7c9a3e.png)

然后会弹出`记录类型不正确`的报错，这时保存键就会处于转圈状态了，并且一直卡在那。
即使按了取消再重新添加记录也没用：
![image](https://user-images.githubusercontent.com/49407099/188850131-512b1779-3b14-4869-a1cb-6f2934be901d.png)

只能通过刷新网页解决。

**Comment by rehiy** [comment]
fixed
