### ISSUE TITLE
cf导入页面会访问不存在的zone id的dns记录，一直返回无权限

### ISSUE THREAD

**Issue by hapke24** [tdp-resource/tdp-cloud#27]
cf导入页面会访问id为3bf29adb3736dda1506aca5084a71dfc的zone的解析记录，但实际账户内并没有这个zone id
但是导入正常

![1675330436317(1)](https://user-images.githubusercontent.com/49407099/216286608-b44bdc74-fd48-4aa6-a892-6345766c9668.png)

![1675330455329](https://user-images.githubusercontent.com/49407099/216286682-da2b3400-0164-44aa-93d8-f1184fb7a31c.png)

**Comment by rehiy** [comment]
抱歉，测试代码带进去了。下次nightbuild删除
