### ISSUE TITLE
导入阿里云资源

### ISSUE THREAD

**Issue by rehiy** [tdp-resource/tdp-cloud#32]
接口部分已完成，UI尚未实现

**Comment by qxbug** [comment]
阿里添加完毕 能看到记录总数  但是看不到域名

**Comment by rehiy** [comment]
抱歉，正在开发中

> 阿里添加完毕 能看到记录总数 但是看不到域名

**Comment by qxbug** [comment]
好的
另外CF的添加完毕也有个报错，5个权限都添加了的
Access to configure this resource has not been granted for this zone. This feature is available with SSL for SaaS

**Comment by rehiy** [comment]
麻烦你进入cf官网，tls里面，看看custom hostnames 是否有权限

**Comment by qxbug** [comment]
这个域名的设置是  Your SSL/TLS encryption mode is Flexible

**Comment by rehiy** [comment]
这个页面看看 

![image](https://user-images.githubusercontent.com/8297757/222071490-22e87617-8913-47b7-93d4-89370516fbfe.png)

**Comment by rehiy** [comment]
已确定问题，这个功能需要添加支付方式后才可用，我尝试添加下提示。

**Comment by qxbug** [comment]
收到 我现在能解析就够用了
